name: mikutter
version: 3.9.0-alpha2
summary: It's moeful
description: |
  TODO

grade: devel
confinement: strict
base: core18

parts:
  desktop-gtk2:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters:
    - FLAVOR=gtk2
    build-packages:
    - libgtk2.0-dev
    stage-packages:
    - libgtk2.0-0
  mikutter:
    after:
    - desktop-gtk2
    source: git://toshia.dip.jp/mikutter.git
    source-tag: 3.9.0-alpha2
    source-depth: 1
    plugin: ruby
    gems:
    - bundler
    build-packages:
    - libidn11-dev # idn-ruby
    override-build: |
      bundle install --without=test
      cp -a .bundle core mikutter.rb Gemfile LICENSE README $SNAPCRAFT_PART_INSTALL
    stage-packages:
    - libglib2.0-0
    - libatk1.0-0
    - libcairo2
    - libcairo-gobject2
    - libgirepository-1.0-1
    - libgdk-pixbuf2.0-0
    - libpango1.0-0
    - libgtk2.0-0
    - gir1.2-atk-1.0
    - gir1.2-gdkpixbuf-2.0
    - gir1.2-gtk-2.0
    - gir1.2-pango-1.0
    - libidn11 # idn-ruby

apps:
  mikutter:
    environment:
      DISABLE_BUNDLER_SETUP: 1
      GI_TYPELIB_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
    command: desktop-launch $SNAP/mikutter.rb
    plugs:
    - x11
    - desktop
    - desktop-legacy
    - network
    - pulseaudio
