name: mikutter
version: 3.9.0-alpha2
summary: It's moeful
description: |
  TODO

  `ln -s ~/.gtkrc2.0 ~/snap/mikutter/current/` to apply gtk2 theme setting.
icon: mikutter.png
license: MIT

grade: devel
confinement: strict
base: core18

plugs:
  gnome-3-28-1804:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-28-1804
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes

parts:
  ruby:
    build-packages:
    - build-essential
    - libssl-dev
    - libreadline6-dev
    - libgdbm-dev
    - zlib1g-dev
    source: https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.3.tar.gz
    plugin: autotools
    configflags:
    - --enable-load-relative
    - --prefix=/usr
    - --disable-install-doc
    prime:
    - -**/*.a
    - -**/*.o
    - -usr/include
    - -usr/lib/pkgconfig
    - -usr/lib/debug
    - -usr/lib/ruby/gems/2.6.0/cache
    - -usr/share
  desktop-helpers:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters:
    - FLAVOR=gtk2
    build-packages:
    - build-essential
    organize:
      bin/desktop-launch: usr/bin/desktop-launch
      lib/bindtextdomain.so: usr/lib/bindtextdomain.so
  gtk2:
    plugin: nil
    stage-packages:
    - libgtk2.0-0
    prime:
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/gtk-2.0
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgdk-x11-2.0.so*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgtk-x11-2.0.so*
    - usr/lib/$SNAPCRAFT_ARCH_TRIPLET/libgtk2.0-0
  mikutter:
    source: git://toshia.dip.jp/mikutter.git
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    plugin: dump
    organize:
      core: app/core
      mikutter.rb: app/mikutter.rb
      Gemfile: app/Gemfile
      LICENSE: app/LICENSE
      README: app/README
    prime:
    - app
  bundle:
    after:
    - ruby
    build-packages:
    - libgtk2.0-dev
    - libidn11-dev # idn-ruby
    build-snaps:
    - gnome-3-28-1804
    source-tag: $SNAPCRAFT_PROJECT_VERSION
    source-depth: 1
    plugin: nil
    override-build: |
      export GEM_HOME=$SNAPCRAFT_PART_INSTALL/usr/lib/ruby/gems/2.6.0
      bundle install --without=test --jobs=$SNAPCRAFT_PARALLEL_BUILD_COUNT
      mkdir $SNAPCRAFT_PART_INSTALL/app
      cp -a .bundle $SNAPCRAFT_PART_INSTALL/app
    stage-packages:
    - libidn11 # idn-ruby
    organize:
      lib/$SNAPCRAFT_ARCH_TRIPLET/libidn.so.11*: usr/lib/$SNAPCRAFT_ARCH_TRIPLET/
    prime:
    - -**/*.o
    - -usr/lib/ruby/gems/2.6.0/cache
    - -usr/lib/ruby/gems/2.6.0/gems/*/ext
    - -usr/share
  mikutter-snap:
    source: .
    plugin: dump
    organize:
      mikutter.desktop: usr/share/applications/mikutter.desktop
    prime:
    - usr/share/applications/mikutter.desktop

apps:
  mikutter:
    common-id: net.hachune.mikutter
    environment:
      DISABLE_BUNDLER_SETUP: 1
      GI_TYPELIB_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/girepository-1.0
      # environment variables for gtk2
      # see https://forum.snapcraft.io/t/improving-theme-support-for-gtk-2-apps/7693
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
    # set necessary environment variables (XDG_DATA_DIRS, GTK_PATH, etc)
    command: desktop-launch $SNAP/app/mikutter.rb
    plugs:
    - x11
    - desktop
    - desktop-legacy
    - network
    - pulseaudio
    desktop: usr/share/applications/mikutter.desktop
