name: mikutter
version: 4.0.0-alpha3
summary: Simple, powerful, and moeful multi-service client (Mastodon, Twitter)
description: |
  Mikutter is a plugin-extensible multi-service client (Mastodon, Twitter).

  **FAQ**  
  Q. How to apply Gtk2 themes?  
  A. `cp ~/.gtkrc2.0 ~/snap/mikutter/current/` to apply gtk2 theme setting.

  Q. How to find plugins?  
  A. See https://github.com/topics/mikutter-plugin .

  Q. How to install plugins?  
  A. Place plugin files in `~/snap/mikutter/current/.mikutter/plugin/`.

  **LINKS**
  * Homepage: https://mikutter.hachune.net/
  * FAQ: https://mikutter.hachune.net/faq
  * Wiki: https://yuzuki.hachune.net/wiki/FrontPage

  **CONTACT**
  * Author: toshi_a
  * Package maintainer: yuntan
icon: snap/gui/mikutter.png
license: MIT

type: app
architectures:
- build-on: amd64
- build-on: i386
- build-on: arm64
- build-on: armhf
grade: stable
confinement: strict
# make the core version matches to gnome platform version
base: core

apps:
  mikutter:
    common-id: net.hachune.mikutter
    environment:
      DISABLE_BUNDLER_SETUP: 1
      # environment variables for gtk2
      # see https://forum.snapcraft.io/t/improving-theme-support-for-gtk-2-apps/7693
      GTK_PATH: $SNAP/lib/gtk-2.0
      GTK_DATA_PREFIX: $SNAP
    # desktop-launch: set necessary environment variables (XDG_DATA_DIRS,
    # GI_TYPELIB_PATH, GTK_PATH, etc), and enable IME
    command: usr/bin/desktop-launch $SNAP/usr/bin/ruby -x $SNAP/app/mikutter.rb
    plugs:
    - x11
    - desktop
    - desktop-legacy
    - network
    - audio-playback

plugs:
  # use gnome-3-26-1604 for libgtk2
  # libgtk2 is required to enable IME
  gnome-3-26-1604:
    interface: content
    target: $SNAP/gnome-platform
    default-provider: gnome-3-26-1604
  gtk-2-engines:
    interface: content
    target: $SNAP/lib/gtk-2.0
    default-provider: gtk2-common-themes
  gtk-2-themes:
    interface: content
    target: $SNAP/share/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/share/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/share/sounds
    default-provider: gtk-common-themes

parts:
  jemalloc:
    source: https://github.com/jemalloc/jemalloc/releases/download/5.2.1/jemalloc-5.2.1.tar.bz2
    plugin: autotools
    configflags:
    - --prefix=/usr

  ruby:
    after:
    - jemalloc
    build-packages:
    - build-essential
    - libssl-dev
    - libreadline6-dev
    - libgdbm-dev
    - zlib1g-dev
    source: https://cache.ruby-lang.org/pub/ruby/2.6/ruby-2.6.5.tar.gz
    plugin: autotools
    configflags:
    - --enable-load-relative
    - --with-jemalloc
    - --prefix=/usr
    - --disable-install-doc
    prime:
    - -**/*.a
    - -**/*.o
    - -usr/include
    - -usr/lib/pkgconfig
    - -usr/lib/debug
    - -usr/lib/ruby/gems/2.6.0/cache
    - -usr/share

  desktop-helpers:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: gtk
    plugin: make
    make-parameters:
    - FLAVOR=gtk2
    build-packages:
    - build-essential
    organize:
      bin/desktop-launch: usr/bin/desktop-launch
      lib/bindtextdomain.so: usr/lib/bindtextdomain.so

  mikutter:
    source: https://mikutter.hachune.net/bin/mikutter.$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: dump
    organize:
      core: app/core
      plugin: app/plugin
      mikutter.rb: app/mikutter.rb
      Gemfile: app/Gemfile
      LICENSE: app/LICENSE
      README: app/README
    prime:
    - app
    - -app/plugin/alsa # remove alsa plugin

  # bundle install
  bundle:
    after:
    - ruby
    build-packages:
    - libgtk2.0-dev
    - libgirepository1.0-dev
    source: https://mikutter.hachune.net/bin/mikutter.$SNAPCRAFT_PROJECT_VERSION.tar.gz
    plugin: nil
    override-build: |
      export GEM_HOME=$SNAPCRAFT_PART_INSTALL/usr/lib/ruby/gems/2.6.0
      bundle install --without=test --jobs=$SNAPCRAFT_PARALLEL_BUILD_COUNT
      mkdir $SNAPCRAFT_PART_INSTALL/app
      cp -a .bundle $SNAPCRAFT_PART_INSTALL/app
    prime:
    - -**/*.o
    - -usr/lib/ruby/gems/2.6.0/cache
    - -usr/lib/ruby/gems/2.6.0/gems/*/ext
    - -usr/share

  # pulseaudio plugin
  mikutter-pulseaudio:
    source: https://github.com/yuntan/mikutter-pulseaudio.git
    plugin: dump
    organize:
      .mikutter.yml: app/plugin/pulseaudio/
      README.md: app/plugin/pulseaudio/
      LICENSE: app/plugin/pulseaudio/
      pulseaudio.rb: app/plugin/pulseaudio/

  # paplay command
  paplay:
    plugin: nil
    stage-packages:
    - pulseaudio-utils

  # notify-send command
  notify-send:
    plugin: nil
    stage-packages:
    - libnotify-bin
